<a href="https://colab.research.google.com/github/Harsh-gupta-07/PyTorch-Notes/blob/main/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Intro to Tensors


###Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

## Tensor dtypes

In [ ]:
float32 = torch.tensor([1.0,2,3,4],
                       dtype=None,
                       device=None,
                       requires_grad=False)

In [ ]:
float32.dtype

torch.float32

In [ ]:
float16 = torch.tensor([1.0,2,3,4],
                       dtype=torch.float16)

In [ ]:
float16.dtype

torch.float16

## Manipulating Tensors

In [ ]:
#add
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#subtract
tensor - 1

tensor([0, 1, 2])

In [ ]:
#multiply
tensor * 100
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiply

In [ ]:
#element wise
tensor = torch.tensor([1,2,3])
tensor * tensor

tensor([1, 4, 9])

In [ ]:
#matrix
torch.matmul(tensor, tensor)

tensor(14)

## Reshaping, stacking, sqeezing and unsqueezing tensors

In [ ]:
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_re = x.reshape(2,5)
x_re, x_re.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# shares memory with x
z = x.view(2,5)
z

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

###Stacking

In [ ]:
torch.stack([x,x,x,x], dim=0)


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
torch.stack([x,x,x,x], dim=1)

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

### Squeezing

In [ ]:
y = x.reshape(1,10)
y

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
# remove single dimensions (dim with one element)
y_sq = y.squeeze_()
y_sq

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# adds a single dimension if shape [10] on dim=0 => [1,10] or dim=1 => [10,1]
y_sq.unsqueeze(dim=0)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

### Permute

In [ ]:
x_original = torch.rand(size=(224,224,5))

In [ ]:
#swap dimensions based on index
x_pre = x_original.permute(2,0,1)

In [ ]:
x_original.shape, x_pre.shape

(torch.Size([224, 224, 5]), torch.Size([5, 224, 224]))

### Indexing

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[:,1,0]

tensor([4])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:,:,0] #all first column element

tensor([[1, 4, 7]])

# PyTorch and numpy

In [ ]:
arr = np.arange(1,10)
tnsor = torch.from_numpy(arr)
arr,tnsor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
arr.dtype, tnsor.dtype #numpy defaults to 64

(dtype('int64'), torch.int64)

In [ ]:
brr = tnsor.numpy()
brr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])